version: "3"

services:

    icedbroccoli:
        build: .
        expose:
            - "3030"
        restart: always

    reverseproccoli:
        build: reverseProccoli
        expose:
            - "80"
        ports:
            - "80:80"
        links:
            - icedbroccoli
        restart: always

    seedingbroccoli:
        build: seedingbroccoli
