version: "3"

services:

    icedbroccoli:
        build: .
        expose:
            - "3030"
        ports:
            - "80:3030"
        environment:
            - ADMIN_PASSWORD
        restart: always
